#!/bin/bash

IFS=$'\n' read -d '' -r -a nodes < nodes.txt

echo "target nodes:"
echo "${nodes[@]}"

echo "target command: $1"

copy_files="./exec ./daemon ./reset ./deploy ./idcreate ./stop ./up ./see ./states ./pskill ./monitor"
# delete_files="./exec ./daemon ./reset ./deploy ./idcreate ./stop ./up ./see ./states ./pskill ./monitor"
delete_files="./exec ./reset ./idcreate"

# some commands such as "see" or "states" are usefull for monitoring

for node in ${nodes[@]}
do
  echo ""
  echo "----------------------------------------------------"
  echo "[$node] RUNNING ..."
  echo ""
  echo "scp files to $node ..."
  scp -q ${copy_files[@]} "$node:"
  # echo "cast 'chmod +x' on files at $node"
  # ssh $node "chmod +x $copy_files"
  echo "execute [$1] at $node"
  echo ""
  ssh $node "chmod +x $copy_files; $1 $node; rm $delete_files"
  echo "DONE"
  echo ""
  # echo "clean up files"
  # ssh $node "rm $delete_files"
done
