#!/bin/bash


./pskill bitdust.py

echo "running 'reset' on $1"

rm -rf bitdust
git clone https://github.com/vesellov/bitdust.devel.git
# git clone http://gitlab.bitdust.io/devel/bitdust.devel.git
mv bitdust.devel bitdust
cd bitdust
git config --global user.email "vesellov@gmail.com"
git config --global user.name "Veselin VPS"
git status
cd ..


echo "running 'deploy' on $1"

cd bitdust
python bitdust.py deploy
cd ..
