#!/bin/bash

IFS=$'\n' read -d '' -r -a nodes < nodes.txt
echo "target nodes:"
echo "${nodes[@]}"
echo "----------------------------------------------------"
for node in ${nodes[@]}
do
  echo "[$node]"
  ssh $node "bitdust idurl; bitdust automats list | grep -e p2p_connector -e network_connector -e tcp_transport -e udp_transport -e ;"
done